### ISSUE TITLE
csv_to_sqlite throws error: `col_names` must be TRUE, FALSE or a character vector

### ISSUE THREAD

**Issue by lkwhite** [inbo/inborutils#116]
First time using this package, I come from a dplyr background but not a SQL one, which may mean I'm missing something obvious with this error.

Here's the entirety of what I'm trying to run to load a tab separated file into a database. The first row of my file does include column names, but if I add col_names = T into the csv_to_sqlite call, I then get error: `formal argument "col_names" matched by multiple actual arguments`. 

```
require(tidyverse)
require(dbplyr)
library(DBI)
library(inborutils)

sqlite_file <- "test.sqlite"
table_name <- "table"

csv_to_sqlite(csv_file = "tabseparatedfile.txt",
              sqlite_file,
              table_name,
              delim="\t",
              pre_process_size = 1000,
              chunk_size = 50000,
              show_progress_bar = T)
```

**Comment by hansvancalster** [comment]
Hi Laura, thanks for reporting. I think I might have addressed a similar issue in https://github.com/inbo/inborutils/pull/115. Can you try if `remotes::install_github("inbo/inborutils@sp-to-sf")` solves your issue?

**Comment by lkwhite** [comment]
Fantastic, that did the trick. Thanks for the quick response!

**Comment by sghignone** [comment]
Hi guys...I'm facing a similar issue with current v0.2.1.
The issue appears both if I call col_names = FALSE or col_names = paste0("X", 1:12) , when I try to load a 12 columns tab separated file, large around a Gb...
Here follows the case with cal_names = FALSE:
![image](https://user-images.githubusercontent.com/7242651/192363080-9bc89567-12ac-40c7-9cf7-a0cb38b38611.png)

I already tried the trick Hans suggested, but the branch was closed some months ago and it's not working..
Any suggestion is welcome.
Ciao


PS.: also specifying n_max = 100000 gives me the error:
`Error in read_delim(csv_file, delim = delim, n_max = pre_process_size,  : 
  formal argument "n_max" matched by multiple actual arguments`

**Comment by hansvancalster** [comment]
Thanks for reporting! This is because `inborutils::csv_to_sqlite()` already uses `col_names` and `n_max` in the body of the function.

The issue with `col_names` you bring up, is a use case (a csv file with no column names) we hadn't yet covered. It should be fixed by d0a681860e3bd13284989400ab46324d1e8bd6a8 which is in the next version of the package. You can already try out by installing the `v0.3.0` branch:

```
remotes::install_github("inbo/inborutils@v0.3.0")
```

The issue with `n_max` is handled as well, but note that passing `n_max` will have no effect (it will be silently dropped). This is because `n_max` is not an argument of `read_delim_chunked` (which is called by `csv_to_sqlite`) and the use cases we have in mind for this function only cover transferring entire csv files to an sqlite table.

**Comment by sghignone** [comment]
Thanks Hans! the new version worked fine with my data. 

Thanks Hans! the new version worked fine with my data.  Nevertheless, I'd like to let you know that the new version does not compile correctly on windows (same error with remote:: or devtools::):
` [...]
\* installing *source* package 'inborutils' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/*****/AppData/Local/Temp/RtmpMfR0Et/R.INSTALL4a685b1e4838/inborutils/R/get_coverage_wcs.R:75:41: unexpected '>'
74: 
75:   matrix(bbox, ncol = 2, byrow = TRUE) |>
                                            ^
ERROR: unable to collate and parse R files for package 'inborutils'
\* removing .....[...] `

**Comment by hansvancalster** [comment]
Nice to know it worked for your data!
The installer seems to trip over the `|>` pipe operator, which I used in one of the functions. You probably have an R version < 4.1.0, because the native pipe operator was introduced from that version onward. If so, I expect the package will compile after you update your R version. After an update of R, it is also recommended to update your packages using `update.packages(ask = FALSE, checkBuilt = TRUE)`.

**Comment by sghignone** [comment]
yah I realized exactly I'm running an old R version. My bad...
