### ISSUE TITLE
Add text datafiles for testing/examples of some functions

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inborutils#37]
While working on #34, I found that no working examples can be written for some functions because no input datafiles are present in `./data/`. The functions are the following:
1. `read_mow_data()`
2. `read_kmi_data()`
3. `read_kml_file()`

**Comment by stijnvanhoey** [comment]
We have a bit of an issue by requiring raw text-files as input of the examples inside roxygen headers. As far as I know (and [stackoverflow](https://stackoverflow.com/questions/12391195/include-data-examples-in-developing-r-packages), cfr. we can not use the `rda` concept here, because the concept is actually to show the reading of text-files). 

Hence, the information is compiled inside a vignette using examples from text files stored in the `/ext/instdata` folder. I added now some dummy examples for the user and a reference to the vignette to help the user.
