### ISSUE TITLE
csv_to_sqlite: bug with cols_only() as value of parameter col_types

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inborutils#42]
I am using this function with optional parameter `col_types = cols_only(...)`.
Unfortunately it seems that the read_delim_chunk callback doesn't read the desired columns but just the first n columns where n is the number of columns in `cols_only()`.

Here below a microexample using `mtcars`:

```r
library(inborutils)
library(tidyverse)
library(glue)

cols_subset <- cols_only(
  mpg = col_double(),
  hp = col_double(),
  gear = col_double()
)

mtcars <- read_csv(readr_example("mtcars.csv"))
write_csv(mtcars, "./mtcars.csv")
mtcars_file <- "./mtcars.csv"
mtcars_sqlite_cols_only <- "./mtcars_sqlite_cols_only.sqlite"
table_name <- "mtcars"

csv_to_sqlite(csv_file = mtcars_file,
              sqlite_file = mtcars_sqlite_cols_only,
                table_name = table_name,
                pre_process_size = 10, 
                chunk_size = 5,
                delim = ",", 
                col_types = cols_subset
)

mtcars_sqlite_cols_only <- dbConnect(SQLite(), dbname = mtcars_sqlite_cols_only)

## Get occurrenceStatus values
query <- glue_sql(
  "SELECT gear FROM {table}",
  table = table_name,
  .con = mtcars_sqlite_cols_only
)
dbGetQuery(mtcars_sqlite_cols_only, query)

# check original data
mtcars
```

As you could see the first 10 (`pre_process_size` value) rows of `gear` are ok as they come from the [internal call to `read_delim()`](https://github.com/inbo/inborutils/blob/master/R/csv_to_sqlite.R#L70). The problem is while calling the `read_delim_chunked()`, specifically the [callback function](https://github.com/inbo/inborutils/blob/master/R/csv_to_sqlite.R#L88).

I tried a lot, e.g. by passing a param `cols_to_select`  to `append_to_sqlite()` function and introducing `x %>% select(cols_to_select)` in the [pipe](https://github.com/inbo/inborutils/blob/master/R/csv_to_sqlite.R#L112).

@stijnvanhoey : any idea? I will buy you a big big big :pizza: if you can solve this!

**Comment by stijnvanhoey** [comment]
What I can tell after a first quick check: the callback itself is not the issue, as what the callback receives is already the subset of first n columns. I also tested with an alternative callback function `f <- function(x, pos) print(x)` and and that just prints out for each chunk the first n columns as well. So, the error is somewhere how `read_delim_chunked` handles internally the `cols_only` argument. No pizza yet...

**Comment by hansvancalster** [comment]
I checked with the latest version of `inborutils` and the bug is not solved. Something to discuss with @inbo/bmk.

**Comment by ElsLommelen** [comment]
The problem seems to appear because of the use of `cols_only()`: it messes up the data: it only saves the given column names but it somehow partly picks the wrong data.  Just replace `cols_only()` by `cols()`, and your code works fine.  In this case it saves the whole table including the columns that are not declared directly.  (`cols_only()` can work fine as well, as long as you add all columns.  ;-) )

I'm not sure which is the best strategy to warn other users to use `cols()` instead of `cols_only()`?  I don't know if it is possible to check which function the user has chosen fo declare `col_types` before writing the sqlite database?  Afterwards, the number of columns in the database table could be checked (it should be equal to the number of colums in the csv file, this problem occurs if this is equal to length(col_types$cols)`).  But then the database is written already, and I don't know how much problems we want to cover with warnings and errors?
